version: "2"

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    build: 
     dockerfile: DockerFile
     context: .
    command : sh -c "/opt/kafka_2.13-2.6.0/bin/kafka-topics.sh --create --zookeeper kafka:2181 --replication-factor 1 --partitions 1 --topic test"
    ports:
      - '9092:9092' 
    environment:
     KAFKA_ADVERTISED_HOST_NAME: "localhost"
     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper
